THEATRE_VERSION_MAJOR    = 0
THEATRE_VERSION_MINOR    = 1
THEATRE_VERSION_REVISION = 0

THEATRE_VERSION = [
    THEATRE_VERSION_MAJOR,
    THEATRE_VERSION_MINOR,
    THEATRE_VERSION_REVISION
].join('.')
